# -*- coding: utf-8 -*-
"""for loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyPiE61r1vEiAUR11jShnkwHBoVmgfjF
"""

#To print 1 to 10 numbers

for numbers in range (1, 11):
  print(numbers)

# factorial of a number
num=1
for number in range(1,6):
  num=num*number

print(num)

# Reverse a the number

user=(input("Enter a number:"))
reverse=""
for digit in user:
  reverse=digit+reverse
print(reverse)

number=input("enter a number:")
count=0
for n in number:
  count=count+1

print(count)

# To reverse the number from 10 to 1
for numbers in range(10,1,-1):
  print(numbers)

# # printing even numbers from 1 to 20
# for numbers in range(1,21):
#   if numbers%2==0:
#    print(numbers)
for numbers in range(2,20,2):
 print(numbers)

# # reverse printing odd numbers from 1 to 20
# for numbers in range(1,21):
#   if numbers%2!=0:
#    print(numbers)
for numbers in range(2,20,2):
 print(numbers)

#print the multiple table of 5
num=5
for i in range(1,11):
  print(num,"x",1,"=",num*i)

for i in range(1,21):
  print()
  for j in range(1,11):
    print(i,"x",j,"=",i*j)

#adding from 1 to 100
total=0

for num in range(1,101):
  total=total+num


print(total)

# adding even number from 0 to 50
total=0

for num in range(2,51,2):
  total=total+num
print(total)

number=input("Enter a number")
sum=0
for addition in number:
  addition=int(addition)
  sum=sum+addition
  print(sum)

#printing palindrome number
number=input("Enter a number:")
reversed_num=""
for digit in number:
  reversed_num=digit + reversed_num

if reversed_num==number:
  print("Its an polindrome")
else:
  print("Not a polindrome")

#Amstrong number

number= input("Enter a number:")
count=len(number)
total=0
for digit in number:
  total=total+int(digit)**count

if total==int(number):
  print("Amstrong number")
else:
  print("Not an amstrong number")

# counting how many number comes under 100
count=0
for i in range(1,101):
  count=count+1
print(count)