# -*- coding: utf-8 -*-
"""operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts8a6sXN3V-wLborQe4HENTpjklYzyS-
"""

# largest of the three numbers
#using nested is condition

x=int(input("enter your number:"))
y=int(input("enter your number:"))
z=int(input("enter your number:"))
if x==y==z:
  print("The three numbers are equal")
else:
  if x>=y:
    if x>=z:
      print("x is the biggest number")
    else:
      print("z is the biggest number")
  else:
      if y>=z:
        print("y is the biggest number")
      else:
        print("z is the biggest number")

balance=5000
amount_withdraw=int(input("Enter your withdraw amount"))


if amount_withdraw %100 !=0:
  print("Invalid amount please enter the multiples of 100.")

elif amount_withdraw <=0:
  print("Invalid amount")

elif amount_withdraw >balance:
  print("Insufficeint balance")

else:
    balance=balance- amount_withdraw
    print("Remaining balance is:",balance)
    print("Sucssfully withdraw")

Balance=5000
deposit=int(input("Enter deposite amount:"))

if deposit<=0:
  print("invalid deposite amount")
elif  deposit>=50000:
  print("Deposite amount is exceeds the limit")
else:
    Balance=Balance+deposit
    print("Successfully deposited")
    print("New Balance:",Balance)

leap_yr=int(input("Enter your year:"))

if leap_yr%400==0:
    print("Leap year")
elif leap_yr%100==0:
      print("NotLeap year")
elif leap_yr%4==0:
  print("Leap year")
else:
   print("Not leap year")

x=int(input('enter tha number:'))
y=int(input('enter the number:'))
a=x+y
print(a)

# x=int(input("enter your name:"))
# y=int(input("enter your digit:"))
# z=x-y
# print(f"subration of the two digit:",{z})


# x=int(input("enter the number:"))
# y=int(input("enter the numer:"))
# z=x*y
# print(z)

x=50
y=5
print(x/y)
print(27%4) #% means give final answer
            #// it give co-efficeient without decimal number
            #/ is shows co-efficient with decimal number

x=2**5 #power values uses **
print(x)

x=int(input("enter the number:"))
y=int(input("enter the number:"))
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x//y)
print(x**y)

# x=int(input("enter the number:"))
# y=int(input("enter the number:"))
# z=x==y
# print(z)
print(40!=18)
print(75>50)
print(12<8)
print(100>=100)
print(45<=30)
print(120==120)
print(35<50)
print(99!=99)

marks=int(input("Enter your marks:"))

if marks>=90:
    print("Grade A")
    if marks>=95:
      print("Outstanding Performence")
elif (marks>=75) and (marks<=89):
       print("Grade B")

elif (marks>=50) and (marks<=75):
       print("Grade C")

else:
  marks<50
  print("Fail")

x=int(input("enter the number:"))
y=int(input("enter the number:"))
z=int(input("enter the number:"))

if x==y==z:
  print("all the numbers are equal")
else:
    if x>=y:
     if x>=z:
      print("x is the biggest number")
     else:
        print("z is the biggest number")
    else:
      if y>=z:
        print("y is the biggest number")
      else:
           print("z is the biggest number")