# -*- coding: utf-8 -*-
"""pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAqPtV2RqxSlVc-X4fztu_e-TjXY6UYN
"""

# pattern printing

for row in range(1,6):
  print("*"*row)

# printing reverse pattern
for row in range(6,0,-1):
  print("*"*row)

for row in range(1,6):
  print(" " * (5 - row) + "*" * (2 * row - 1))

for row in range(7,-1,-1):
  print(" "*(7-row)+ "*" *(2*row-1))

#printing numbers
for row in range(1,6):
  for i in range(1,row+1):
    print(i ,end="")
  print()