# -*- coding: utf-8 -*-
"""Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myvmeOuNAm5lIYZPzPbbK1HbwE_8NJpc
"""

name='devika'
print(name)

age=20
city='puttur'
print(f"i am {age} old. i lived in {city} ")

# input function----->
user_input=input("whats is your name?")
age=input("enter your age:")
print(f"hello {user_input},your are{age} years old")

fav_color=input("enter your fav color?")
fav_food=input("enter your fav food?")
fav_job=input("what's your fav job?")
print(f"my fav color is {fav_color},and i love {fav_food}, my dream job is {fav_job}")

a=10
b=34
a,b=b,a
print(a)
print(b)

salary=50000
x=salary+5000
print(x)

25
'python'
3.14
True
type(25)
type('python')
type(3.14)
type(True)































#using commas---->
age=20
city="puttur"
print("I am ",age, "Years old.  I lived in",city,"since 20yr")

#using f string---->
age=20
print(f"i am {age} years old, I lived in {city} since 20yr")

#using formatting--->
age =20
city='puttur'
print("i am {} years old, I lived in {} since 20yr".format((age),(city)))

a=10
b=20
print(a+b)

city="warangal"
country='india'
print((city ) ,(country))



price=500
print("The price is",price)

frist_name='devika'
last_name='chandragiri'
print(frist_name,last_name)

python_marks=85
sqi_marks=90
powerbi_marks=88
print(python_marks+sqi_marks+powerbi_marks)

length=10
width=5
x=length*width
print("Area of the retangle:",x)





















