# -*- coding: utf-8 -*-
"""while loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dgHenDxAeEXo_-Ov6uJ8e0tLHm0ONqeJ
"""

#printing reverse number
number=11
while number>0:
  number=number-1
  print(number)

#printing from 1 to 10

number=0
while number<10:
  number=number+1
  print(number)

#printing even number from 1 to 20

number=1
while number<=20:
  if number%2 ==0:
   print(number)
  number=number+1

# printing odd from 1 to 20

number=1
while number<=20:
  if number%2 !=0:
   print(number)
  number=number+1

#sum of 1 to 100
number=1
sum=0
while number<=100:
    sum=sum+number
    number=number+1


print(sum)

#adding 1 to 50 even numbers
number=1
sum=0
while number<=50:
  if number%2 ==0:
    sum=sum+number
  number=number+1

print(sum)

# adding odd number from 1 to 50

number=1
sum=0
while number<=50:
  if number%2 !=0:
    sum=sum+number
  number=number+1
print(sum)

#print the multiplication of table 7
number=1
while number<=10:
 mul=number*7
 print("7","x",number,"=",mul)
 number=number+1

#count 1 to 100 numbers
number=1
count=0
while number<=100:
  count=count+1
  number=number+1

print(count)

#Factorial of a number

number=int(input("Enter a number:"))
factorial=1
while number >0:
   factorial=number*factorial
   number=number-1
print(factorial)

#reverse a number
number=int(input("Enter a number:"))
reverse=0
last_digit=0
while number>0:
  Last_digit=number%10
  reverse=Last_digit+reverse*10
  number=number//10
print(reverse)

#check whether the palindrome
number=int(input("Enter a number:"))
reverse=0
final=number
Last_digit=0
while number>0:   #123
  last_digit=number%10 #3
  reverse=last_digit+reverse*10 #3+0*10
  number=number//10

if final==reverse:
   print("Its a polindrome number")
else:
   print("Not a polindrome")

#find the sum of digits of a number
number=int(input("Enter a number:"))
Last_digit=0
sum=0
while number>0:
   last_digit=number%10
   sum=last_digit+sum
   number=number//10



print(sum)

#count the number
number=int(input("Enter a number:"))
count=0
last=0
while number>0:
  last=number%10
  count+=1
  number=number//10

print(count)

#product of the number
number=int(input("Enter a number:"))
last=0
mult=1
while number>0:
  last=number%10
  mult*=last
  number=number//10

print(mult)

# check whether number is Amstronge number are not
number=int(input("Enter a number:"))
temp=number
amg=0
count=len(str(number))
while temp >0:
  last=temp%10
  amg=amg+(last**count)
  temp//=10

if amg==number:
 print("Amstronge number")
else:
   print("Not a amstrong number")

#Fibbonacci series

number=int(input("Enter a number:"))
first=0
second=1
while number>0:
  print(first)
  feb=first+second
  first=second
  second=feb


  number=number-1

#calculating the power of number without using **
base=int(input("Enter a number:"))
exponent=int(input("Enter a exponent number:"))
result=1
while exponent>0:
  result=base*result

  exponent=exponent-1

print(result)

#Find the largest digit in a number
number=int(input("Enter a number:"))
largest=0
while number>0:
  last_digit=number%10
  if last_digit>largest:
     largest=last_digit
  number=number//10

print("largest number is:",largest)